### ISSUE TITLE
Unhandled exception when calling Metrics.Close 

### ISSUE THREAD

**Issue by spacecoder007** [nblumhardt/influxdb-lineprotocol#4]
I have several metrics setup to increment, measure and time. A using statement has been used to dispose of a metric timer. On calling Metrics.Close, the following Unhandled Exception is logged:

Unhandled exception: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxDB.Collector.Platform.PortableTimer.<Start>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by nblumhardt** [comment]
Thanks for the note! Not sure what might be causing this, a busy week here so any help with tracking it down/fixing would be appreciated. Will take a look as soon as possible. Thanks again! :-)

**Comment by spacecoder007** [comment]
Ok thanks, I'll also look into it as well.
